name: Maven Test

on:
  push:
    branches:
      - master # replace with your branch name if not 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.1-eclipse-temurin-20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build artifacts
        run: mvn package
      - name: Archive jar
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./target/*.jar

  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.1-eclipse-temurin-20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Maven test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: alpinelinux/docker-cli
    steps:
      - name: Download jar
        steps: actions/download-artifact@v3
        with:
          name: Build
      - name: Login to docker
        steps: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build image
        steps: docker build -t dadepu/image:1 -t dadepu/image:latest
      - name: Push image
        steps: docker push dadepu/image:1
