name: Feature CI-Workflow

on:
  push:
    branches-ignore:
      - master


env:
  POSTGRES_IMAGE: postgres:15.3
  JAVA_VER: 17
  JAVA_DIST: temurin

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      postgres_image: $POSTGRES_IMAGE
      java_ver: $JAVA_VER
      java_dist: $JAVA_DIST