name: Feature CI-Workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK + Maven
        uses: actions/setup-java@3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
          cache: maven

      - name: Run Tests
        run: mvn test