name: Feature CI-Workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      postgres_image: postgres:15.3
      java_ver: 17
      java_dist: temurin