name: Feature CI-Workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      postgres_image: ${{ vars.POSTGRES_IMAGE }}
      java_ver: ${{ vars.JAVA_VER }}
      java_dist: ${{ vars.JAVA_DIST }}