name: Master CD-Workflow

on:
  push:
    branches:
      - master

env:
  POSTGRES_IMAGE: postgres:15.3
  JAVA_VER: 17
  JAVA_DIST: temurin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK + Maven
        uses: actions/setup-java@v3
        with:
          distribution: $JAVA_DIST
          java-version: $JAVA_VER
          java-package: jdk
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Push Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./target/*.jar
          retention-days: 1

  test:
    uses: ./.github/workflows/test.yml
    with:
      postgres_image: $POSTGRES_IMAGE
      java_ver: $JAVA_VER
      java_dist: $JAVA_DIST

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Dockerfile

      - name: Download Jar
        uses: actions/download-artifact@v3
        id: artifact-download
        with:
          name: build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/github:latest
          build-args: |
            JAR_INPUT_DIR=.
