name: Unit-Test Workflow

on:
  workflow_call:
    inputs:
      postgres_image:
        default: 'postgres:15.3'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ${{ inputs.postgres_image }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432